#!/usr/bin/env python3

import argparse

import pywikibot

from coalemosBot import CoalemosBot

from club import Club

pages = [
    "Équipe_d'Argentine_masculine_de_handball"
]

def parse_args():
    parser = argparse.ArgumentParser(
        prog='Coalemos',
        description='Use many scripts to improve Wikipedia'
    )
    parser.add_argument('-a', '--all', action='store_true', help='Execute all scripts')
    parser.add_argument('--auto', action='store_true', default=False, help="Work without verification")

    parser.add_argument('--contributions', action='store_true', help='Update contributions for users')
    parser.add_argument('--internalLinks', action='store_true', help='Replace Links into pages')
    parser.add_argument('--unusedRedirect', action='store_true', help='List unusedRedirect into bot page (/bot/UnusedRedirect)')

    args = parser.parse_args()
    if args.all:
        args.contributions = True
        args.internalLinks = True
        args.unusedRedirect = True

    return args

if __name__ == '__main__':
    args = parse_args()

    coalemos = CoalemosBot(pages, args.auto)
    # coalemos.addCategory("Équipe nationale de handball")
    # coalemos.addCategory("Championnat panaméricain féminin de handball")
    # coalemos.addCategory("Championnat panaméricain masculin de handball")

    if args.contributions:
        coalemos.updateUserContributionsBox()
    elif args.internalLinks:
        coalemos.fixInternalLinks()
    elif args.unusedRedirect:
        coalemos.getUnusedRedirect()
    else:
        print("No instruction given")

    # coalemos.translate("1981 Pan American Men's Handball Championship")
