#!/usr/bin/env python3

import pywikibot

from coalemosBot import CoalemosBot

from club import Club

clubs = [
    'Stade_français_Paris_rugby'
]

pages = [
    "Modèle:Feuille de match handball",
]

site = pywikibot.Site();
site.login()

coalemos = CoalemosBot(site, pages)
# coalemos.addCategory("Handball")
# coalemos.addCategory("Équipe nationale de handball")
# coalemos.addCategory("Championnat panaméricain féminin de handball")
# coalemos.addCategory("Championnat panaméricain masculin de handball")
# coalemos.cleanRedirect()

coalemos.updateUserContibutions('Programmateur01')



# coalemos.cleanDraft()
